POST https://roldan-personal-recipes.herokuapp.com/api/v1/recipes
Content-Type: application/json

{
  "recipeName": "Grilled Cheese Sandwich",
  "recipeImg": "https://natashaskitchen.com/wp-content/uploads/2021/08/Grilled-Cheese-Sandwich-3.jpg",
  "recipeIngredients": [
      {
          "name": "Slices of Bread",
          "quantity": 2
      },
      {
          "name": "Tbsp of Butter",
          "quantity": 0.5
      },
      {
          "name": "Cheese slices",
          "quantity": 2
      }
  ],
  "recipeTools": [
      {
          "name": "Skillet",
          "size": "A good size"
      }
  ],
  "recipeSteps": [
      "Butter the toast - spread 1/2 Tbsp butter on one side of each slice of bread.",
      "Heat skillet - place a skillet over low to medium/low heat. A griddle should be at 275˚F. Immediately add 2 slices of bread with the butter-side-down.",
      "Add cheese - stack cheeses on one of the pieces of bread, cover with the other piece of toast and flip the sandwich over.",
      "Brown the toast - Continue sauteeing, flipping once, until both sides are golden brown and cheese is melted.",
      "Serve - cut the sandwich in half on the diagonal to serve."
  ]
}

###